messages:
  specify_player: "&cSpecify a player."
  player_banned: "&aSuccessfully banned player {player}."
  player_unbanned: "&aSuccessfully unbanned player {player}."
  no_bans: "&cThe player {player} doesnt have any active bans."
  player_offline: "&cThe player {player} isn't online."
  already_banned: "&cThe player {player} is already banned."
  invalid_duration: "&cEnter a valid ban duration."
  not_available: "&cThe ban service isn't available yet."
