database:
  host: 'localhost'
  port: '3306'
  db: 'bans'
  username: 'root'
  password: 'admin'

messages:
  specify_player: "&cSpecify a player."
  player_banned: "&aSuccessfully banned player {player}."
  player_unbanned: "&aSuccessfully unbanned player {player}."
  no_active_bans: "&cThe player {player} doesnt have any active bans."
  no_bans: "&cThe player {player} has never been banned."
  player_offline: "&cThe player {player} isn't online."
  already_banned: "&cThe player {player} is already banned."
  invalid_duration: "&cEnter a valid ban duration."
  not_available: "&cThe ban service isn't available yet."
  player_cmd: "&cCommand only available for player."
  you_are_banned: "&cYou are banned"
  reason_info: "&eReason: &7{reason}"
  end_in: "&cEnds in {months} months, {days} days, {hours} hours, {minutes} minutes and {seconds} seconds"

